# Generated by Django 6.0 on 2025-12-05 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(verbose_name="Данные игры")),
                (
                    "version",
                    models.IntegerField(verbose_name="Версия схемы сотояния игры"),
                ),
                (
                    "gamer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game",
                        to="users.gamer",
                        verbose_name="Игрок",
                    ),
                ),
            ],
        ),
    ]
