# Generated by Django 6.0 on 2026-01-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamer",
            name="code",
            field=models.IntegerField(null=True, verbose_name="Табельный номер"),
        ),
    ]
